#
# Makefile
#
# $Id$
#
# Makefile for app server 
#

include $(POCO_BASE)/build/rules/global

objects = AppServer

target         = app
target_version = 1
target_libs    = PocoOSP PocoZip PocoUtil PocoJSON PocoXML PocoFoundation

include $(POCO_BASE)/build/rules/exec
